name: Update .env from PUBLIC_IP

on:
  workflow_dispatch:  # puedes ejecutarlo manualmente
  repository_dispatch:  # se activa desde fuera (ej: Terraform)

permissions:
  contents: write

jobs:
  update-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env from template
        run: |
          echo "Generando .env con IP ${{ vars.PUBLIC_IP }}"
          sed "s/{{PUBLIC_IP}}/${{ vars.PUBLIC_IP }}/g" .env.template > .env

      - name: Commit and push .env if it changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .env
          if git diff --cached --quiet; then
            echo "No hay cambios en .env"
          else
            git commit -m "Actualiza .env con nueva PUBLIC_IP ${{ vars.PUBLIC_IP }}"
            git push
          fi

